package src.entities;

public enum Allergens {
    GLUTEN_FREE,
    LACTOS_FREE,
    CRUSTACEAND_AND_DERIVATES_FREE,
    EGGS_AND_DERIVATES_FREE,
    FISH_AND_DERIVATES_FREE,
    PEANUTS_AND_DERIVATES_FREE,
    NUTS_AND_DERIVATES_FREE;

}

