package src.entities;

public enum Allergens {
    GLUTEN,
    LACTOS,
    CRUSTACEAND_AND_DERIVATES,
    EGGS_AND_DERIVATES,
    FISH_AND_DERIVATES,
    PEANUTS_AND_DERIVATES,
    NUTS_AND_DERIVATES;

}

